<script lang="ts">
import InputBlock from './InputBlock.vue'
import { CaretPos } from '../assets/js/caretPos'
import { strInsert } from '../assets/js/utils'


export default {
    name: 'Editor',
    components: {
        InputBlock
    },
    data() {
        return {
            blocks: [
                { id: 1, content: 'This is an input block.' },
                { id: 2, content: 'This is another input block.' },
                { id: 3, content: 'This is the last input block.' },
            ],
            renderedMd: {
                type: String,
                default: '<p>Nothing to render.</p>',
            }
        }
    },
    methods: {
        renderAll() {
            /**
             * Loop through each input block, concatenate the HTML result.
             */
            console.log('renderAll')
           
            console.log('blocks', this.blocks)
            // let inputBlocks = this.$refs.inputBlocks
            // let numBlocks = inputBlocks.length
            // for (let i = 0; i < numBlocks; ++i) {
            //     console.log(inputBlocks[i].getContent())
            // }

            // var BLOCK_CONTAINER = ref(document.getElementById('input-container') as HTMLDivElement)
            // var MD_CONTAINER = ref(document.getElementById('md-container') as HTMLDivElement)
            // let numBlocks = BLOCK_CONTAINER.value.children.length
            // if (numBlocks) {
            //     for (let i = 0; i < numBlocks; i++) {
            //         let block = BLOCK_CONTAINER.value?.children[i] as HTMLDivElement
            //     }
            //     MD_CONTAINER.value.innerHTML = htmlResult
            // }
        },

        onInputBlockKeyup(blockId: number, event: KeyboardEvent): void {
            console.log('onInputBlockKeyup', event)
            this.renderAll()
        },
        
        
        onInputBlockKeydown(block: typeof InputBlock, event: KeyboardEvent): void {
            
            let caretPos: CaretPos = block.getCaretPos()
            let content: string = block.getContent()

            // Get the class variable for the block's content (stored in this)
            let blockContent = this.blocks[block.blockId - 1].content
            
            console.log('Inserting text')
            console.log('caretPos', caretPos)
            console.log('content', content)
            console.log('blockContent', blockContent)
            blockContent = strInsert(blockContent, event.key, caretPos.col)

            this.blocks[block.blockId - 1].content = blockContent
        },
    
        // insertTextToBlock(block: typeof InputBlock, text: string, pos: number): void {
        //     console.log('insertTextToBlock', blockId, text, pos)
        // }
    },
    mounted: function () {
        this.renderAll()
    },
}

</script>
    
<template>
    <div id="editor-container">
        <div id="input-container">
            <!-- Input blocks here -->
            <InputBlock 
                v-for="block in blocks" 
                ref="inputBlocks"
                :key="block.id" 
                :blockId="block.id"
                :initialContent="block.content"
                @input-block-keydown="onInputBlockKeydown" 
                @input-block-keyup="onInputBlockKeyup" />
        </div>
        <div id="preview-container">
            <link href="../styles/github.css" rel="stylesheet">
            <!-- The HTML content be generated by the Markdown renderer -->
            <div id="md-container" class="markdown-body" v-html="renderedMd">
            </div>
        </div>
    </div>
</template>
                    
<style scope>
/* This should be moved to parent component */
#editor-container {
    display: flex;
    flex-direction: row;
    height: calc(100% - 20px - 26px);
}

#input-container {
    font-family: 'Ubuntu Mono', 'Consolas', 'Courier New', Courier, monospace;
    font-size: 14px;
    width: 50%;
    height: auto;
    padding: 8px;
    margin: 0;
    overflow: auto;
    background-color: #eeeeee;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    gap: 4px;
    /* white-space: pre-wrap; */

    /* Scrollbar */
    scrollbar-width: thin;
    scrollbar-color: rgba(99, 99, 99, 0.2) rgba(99, 99, 99, 0.2);
}

#preview-container {
    padding: 8px;
    width: 50%;
    margin: 0;
    border-left: rgba(99, 99, 99, 0.2) 1px solid;
    /* background-color: bisque; */
    overflow: auto;
    font-size: 14px;

    /* Scrollbar */
    scrollbar-width: thin;
    scrollbar-color: rgba(99, 99, 99, 0.2) rgba(99, 99, 99, 0.2);
}
</style>