<script lang="ts">
import InputBlock from './InputBlock.vue'

export default {
    name: 'Editor',
    components: {
        InputBlock
    },
    data() {
        return {
            blocks: [
                { id: 0, content: 'block 0' },
                { id: 1, content: 'block 1' },
                { id: 2, content: 'block 2' },
            ],
            renderedMd: '<p>Nothing to render.</p>',
        }
    },
    methods: {
        renderAll() {
            /**
             * Loop through each input block, concatenate the HTML result.
             */
            console.debug('renderAll')
            let inputBlocks = this.$refs.inputBlocks as (typeof InputBlock)[]
            let numBlocks = inputBlocks.length
            this.renderedMd = ''
            for (let i = 0; i < numBlocks; ++i) {
                // console.debug(inputBlocks[i].getContent())
                let a = inputBlocks[i] as unknown as { render(): string}
                this.renderedMd += a.render()
            }
        },

        onInputBlockKeyup(blockId: number, event: KeyboardEvent): void {
            console.log('onInputBlockKeyup', event)
            this.renderAll()
        },

        onContentUpdate(blockId: number, content: string): void {
            console.log('onContentUpdate', blockId, content)
            this.renderAll()
        },

        // insertTextToBlock(block: typeof InputBlock, text: string, pos: number): void {
        //     console.log('insertTextToBlock', blockId, text, pos)
        // }
        newBlockAfter(block: typeof InputBlock, initText: string): void {
            console.log('newBlockAfter', block, initText)
            let blockId = block.blockId
            this.blocks.splice(
                blockId, 0, { id: blockId, content: initText} )
            let inputBlock = this.$refs.inputBlocks as (typeof InputBlock)[]
            inputBlock[blockId].focus()
        },
        onGotoNextBlock(block: typeof InputBlock): void {
            let blockId = block.blockId
            let inputBlocks = this.$refs.inputBlocks as (typeof InputBlock)[]
            if (blockId < inputBlocks.length - 1) {
                inputBlocks[blockId + 1].focus()
                inputBlocks[blockId + 1].moveCaretToStart()
            }
        },
        onGotoPrevBlock(block: typeof InputBlock): void {
            let blockId = block.blockId
            let inputBlocks = this.$refs.inputBlocks as (typeof InputBlock)[]
            if (blockId > 0) {
                inputBlocks[blockId - 1].focus()
                inputBlocks[blockId - 1].moveCaretToEnd()
            }
        },
    },
    mounted: function () {
        this.renderAll()
    },
}

</script>
    
<template>
    <div id="editor-container">
        <div id="input-container">
            <!-- Input blocks here -->
            <InputBlock v-for="block in blocks" 
                ref="inputBlocks" 
                :key="block.id" 
                :blockId="block.id"
                :initialContent="block.content" 
                @new-block-after="newBlockAfter"
                @content-update="onContentUpdate" 
                @goto-next-block="onGotoNextBlock"
                @goto-prev-block="onGotoPrevBlock"
                />
        </div>
        <div id="preview-container">
            <link href="../styles/github.css" rel="stylesheet">
            <!-- The HTML content be generated by the Markdown renderer -->
            <div id="md-container" class="markdown-body" v-html="renderedMd">
            </div>
        </div>
    </div>
</template>
                    
<style scope>
/* This should be moved to parent component */
#editor-container {
    display: flex;
    flex-direction: row;
    height: calc(100% - 20px - 26px);
}

#input-container {
    font-family: 'Ubuntu Mono', 'Consolas', 'Courier New', Courier, monospace;
    font-size: 14px;
    width: 50%;
    height: auto;
    padding: 8px;
    margin: 0;
    overflow: auto;
    background-color: #eeeeee;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    gap: 4px;
    /* white-space: pre-wrap; */

    /* Scrollbar */
    scrollbar-width: thin;
    scrollbar-color: rgba(99, 99, 99, 0.2) rgba(99, 99, 99, 0.2);
}

#preview-container {
    padding: 8px;
    width: 50%;
    margin: 0;
    border-left: rgba(99, 99, 99, 0.2) 1px solid;
    /* background-color: bisque; */
    overflow: auto;
    font-size: 14px;

    /* Scrollbar */
    scrollbar-width: thin;
    scrollbar-color: rgba(99, 99, 99, 0.2) rgba(99, 99, 99, 0.2);
}
</style>