<script lang="ts">
import InputBlock from './InputBlock.vue'

export default {
    name: 'Editor',
    components: {
        InputBlock
    },
    data() {
        return {
            blocks: [
                { id: 1, content: 'block 1' },
                { id: 2, content: 'block 2' },
                { id: 3, content: 'block 3' },
            ],
            renderedMd: '<p>Nothing to render.</p>',
        }
    },
    methods: {
        renderAll() {
            /**
             * Loop through each input block, concatenate the HTML result.
             */
            console.log('renderAll')
            let inputBlocks = this.$refs.inputBlocks as Array<typeof InputBlock>
            let numBlocks = inputBlocks.length
            this.renderedMd = ''
            for (let i = 0; i < numBlocks; ++i) {
                let inputBlock = inputBlocks[i] as typeof InputBlock
                this.renderedMd += inputBlock.render()
            }
        },

        onInputBlockKeyup(blockId: number, event: KeyboardEvent): void {
            console.log('onInputBlockKeyup', event)
            this.renderAll()
        },

        onContentUpdate(blockId: number, content: string): void {
            console.log('onContentUpdate', blockId, content)
            this.renderAll()
        },

        // insertTextToBlock(block: typeof InputBlock, text: string, pos: number): void {
        //     console.log('insertTextToBlock', blockId, text, pos)
        // }
        newBlockAfter(block: typeof InputBlock, initText: string): void {
            let blockId = block.blockId
            this.blocks.splice(
                blockId, 0, { id: blockId + 1, content: initText} )
        }
    },
    mounted: function () {
        this.renderAll()
    },
}

</script>
    
<template>
    <div id="editor-container">
        <div id="input-container">
            <!-- Input blocks here -->
            <InputBlock v-for="block in blocks" ref="inputBlocks" :key="block.id" :blockId="block.id"
                :initialContent="block.content" 
                @input-block-keyup="onInputBlockKeyup"
                @new-block-after="newBlockAfter"
                @content-update="onContentUpdate" />
        </div>
        <div id="preview-container">
            <link href="../styles/github.css" rel="stylesheet">
            <!-- The HTML content be generated by the Markdown renderer -->
            <div id="md-container" class="markdown-body" v-html="renderedMd">
            </div>
        </div>
    </div>
</template>
                    
<style scope>
/* This should be moved to parent component */
#editor-container {
    display: flex;
    flex-direction: row;
    height: calc(100% - 20px - 26px);
}

#input-container {
    font-family: 'Ubuntu Mono', 'Consolas', 'Courier New', Courier, monospace;
    font-size: 14px;
    width: 50%;
    height: auto;
    padding: 8px;
    margin: 0;
    overflow: auto;
    background-color: #eeeeee;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    gap: 4px;
    /* white-space: pre-wrap; */

    /* Scrollbar */
    scrollbar-width: thin;
    scrollbar-color: rgba(99, 99, 99, 0.2) rgba(99, 99, 99, 0.2);
}

#preview-container {
    padding: 8px;
    width: 50%;
    margin: 0;
    border-left: rgba(99, 99, 99, 0.2) 1px solid;
    /* background-color: bisque; */
    overflow: auto;
    font-size: 14px;

    /* Scrollbar */
    scrollbar-width: thin;
    scrollbar-color: rgba(99, 99, 99, 0.2) rgba(99, 99, 99, 0.2);
}
</style>